//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAQCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanhBaoNhapHang
    {
        public int MaCanhBao { get; set; }
        public Nullable<int> MaNguyenLieu { get; set; }
        public Nullable<int> SoLuongHienTai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> IsResolved { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
