//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAQCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguyenLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguyenLieu()
        {
            this.CanhBaoNhapHangs = new HashSet<CanhBaoNhapHang>();
        }
    
        public int MaNguyenLieu { get; set; }
        public string TenNguyenLieu { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> MucCanhBao { get; set; }
        public string NguonMua { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CanhBaoNhapHang> CanhBaoNhapHangs { get; set; }
    }
}
